name: Deploy SSGG_GetAttendance lambda function
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - Lambda/SSGG_GetAttendance/*
      - .github/workflows/SSGG_GetAttendance.yml
jobs:
  checkout-package-and-deploy-source:
    name: Package and deploy source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set Service Name
        id: set-service-name
        run: |
          branch_name="${GITHUB_REF##*/}"
          if [ "$branch_name" == "main" ]; then
            service_name="SSGG_GetAttendance"
            host=${{ secrets.HOST }}
            port=${{ secrets.PORT }}
            database=${{ secrets.DATABASE }}
            user=${{ secrets.USERNAME }}
            password=${{ secrets.PASSWORD }}
          elif [ "$branch_name" == "staging" ]; then
            service_name="SSGG_GetAttendance_STG"
            host=${{ secrets.HOST_STG }}
            port=${{ secrets.PORT_STG }}
            database=${{ secrets.DATABASE_STG }}
            username=${{ secrets.USERNAME_STG }}
            password=${{ secrets.PASSWORD_STG }}
          else
            service_name="SSGG_GetAttendance_$branch_name"
          fi
          echo "service_name=$service_name" >> $GITHUB_OUTPUT
          echo "host=$host" >> $GITHUB_OUTPUT
          echo "port=$port" >> $GITHUB_OUTPUT
          echo "database=$database" >> $GITHUB_OUTPUT
          echo "user=$user" >> $GITHUB_OUTPUT
          echo "password=$password" >> $GITHUB_OUTPUT
      - name: Package source
        run: zip -j ${{ steps.set-service-name.outputs.service_name }}.zip Lambda/SSGG_GetAttendance/*
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Check if Lambda Function Exists
        id: lambda-exists
        run: |
          lambda_name="${{ steps.set-service-name.outputs.service_name }}"
          if aws lambda get-function --function-name $lambda_name 2>/dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Create Lambda Function if does not exist
        if: steps.lambda-exists.outputs.exists == 'false'
        run: |
          lambda_name="${{ steps.set-service-name.outputs.service_name }}"
          aws lambda create-function \
            --function-name $lambda_name \
            --runtime python3.11 \
            --role arn:aws:iam::998833888842:role/Default_Lambda_Basic_Execution_Role \
            --handler lambda_function.lambda_handler \
            --timeout 60 \
            --architectures arm64 \
            --zip-file fileb://${{ steps.set-service-name.outputs.service_name }}.zip \
            --environment "Variables={database=${{ steps.set-service-name.outputs.database }},host=${{ steps.set-service-name.outputs.host }},password=${{ steps.set-service-name.outputs.password }},port=${{ steps.set-service-name.outputs.port }},username=${{ steps.set-service-name.outputs.username }}}" \
            --layers arn:aws:lambda:eu-north-1:998833888842:layer:pymysql:3
      - name: Update Lambda Function
        if: steps.lambda-exists.outputs.exists == 'true'
        run: |
          lambda_name="${{ steps.set-service-name.outputs.service_name }}"
          aws lambda update-function-code \
            --function-name $lambda_name \
            --zip-file fileb://${{ steps.set-service-name.outputs.service_name }}.zip
          aws lambda update-function-configuration \
            --function-name $lambda_name \
            --timeout 60 \
            --environment "Variables={database=${{ steps.set-service-name.outputs.database }},host=${{ steps.set-service-name.outputs.host }},password=${{ steps.set-service-name.outputs.password }},port=${{ steps.set-service-name.outputs.port }},username=${{ steps.set-service-name.outputs.username }}}" \
            --runtime python3.11
      