name: Deploy SSGG-GetMember lambda function
on:
  push:
    branches:
      - main
    paths:
      - Lambda/SSGG-GetMember
jobs:
  checkout-package-and-deploy-source:
    name: Package and deploy source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Package source
        run: zip -j SSGG-APP_GetMember.zip Lambda/SSGG-GetMember/*
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Deploy source
        run: aws lambda update-function-code --function-name=SSGG-GetMember --zip-file=fileb://SSGG-GetMember.zip
      