name: Deploy SSGG_SearchMembers lambda function
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Lambda/SSGG_SearchMembers/*
      - .github/workflows/SSGG_SearchMembers.yml
jobs:
  checkout-package-and-deploy-source:
    name: Package and deploy source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Package source
        run: zip -j SSGG_SearchMembers.zip Lambda/SSGG_SearchMembers/*
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy source
        run: aws lambda update-function-code --function-name=SSGG_SearchMembers --zip-file=fileb://SSGG_SearchMembers.zip
      