name: Deploy SSGG_GetMember lambda function
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Lambda/SSGG_GetMember/*
      - .github/workflows/SSGG_GetMember.yml
jobs:
  checkout-package-and-deploy-source:
    name: Package and deploy source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Package source
        run: zip -j SSGG_GetMember.zip Lambda/SSGG_GetMember/*
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Check if Lambda Function Exists
        id: lambda-exists
        run: |
          lambda_name="SSGG_GetMember"
          if aws lambda get-function --function-name $lambda_name 2>/dev/null; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi
      - name: Create Lambda Function if does not exist
        if: steps.lambda-exists.outputs.exists == 'false'
        run: |
          lambda_name="SSGG_GetMember"
          aws lambda create-function \
            --function-name $lambda_name \
            --runtime python3.10 \
            --role arn:aws:iam::998833888842:role/Default_Lambda_Basic_Execution_Role \
            --handler lambda_handler \
            --zip-file fileb://SSGG_GetMember.zip \
            --environment "Variables={database=${{ secrets.DATABASE }},host=${{ secrets.HOST }},password=${{ secrets.PASSWORD }},port=${{ secrets.PORT }},username=${{ secrets.USERNAME }}}"
            --layers arn:aws:lambda:eu-north-1:998833888842:layer:pymysql:3
      - name: Update Lambda Function
        if: steps.lambda-exists.outputs.exists == 'true'
        run: |
          lambda_name="SSGG_GetMember"
          aws lambda update-function-code \
            --function-name $lambda_name \
            --zip-file fileb://SSGG_GetMember.zip
          aws lambda update-function-configuration \
            --function-name $lambda_name \
            --environment "Variables={database=${{ secrets.DATABASE }},host=${{ secrets.HOST }},password=${{ secrets.PASSWORD }},port=${{ secrets.PORT }},username=${{ secrets.USERNAME }}}"

      