name: Deploy lambda function from source
on: [push]
jobs:
  deploy_source:
    name: Deploy lambda function from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}
      - run: zip -j SSGG-APP_GetMember.zip ./Lambda/SSGG-APP_GetMember/main.py
      - run: aws lambda update-function-code --function-name=SSGG-APP_GetMember --zip-