name: Deploy <Service_Name> lambda function
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - SwaggerUI
      - .github/workflows/UpdateSwaggerUI.yml
jobs:
  checkout-package-and-deploy-source:
    name: Package and deploy source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Update Swagger bucket
        run: |
          aws s3 sync dist s3://ssgg-swagger/